### ISSUE TITLE
New step-builder UI inconsistency: Empty mapping field

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/webhook-component#53] opened 2022-02-11 08:34 UTC
After UI update we have an inconsistency in step-builder. It shows an empty Mapping section:
<img width="832" alt="Screenshot 2022-02-11 at 09 32 45" src="https://user-images.githubusercontent.com/11753582/153560104-c1f00a12-d8f7-47c7-ba7e-64451270187a.png">

**Comment by jhorbulyk** [comment] 2022-02-11 12:07
This might be caused by the definition of `in` metadata here: https://github.com/elasticio/webhook-component/blob/master/component.json#L25

**Comment by jhorbulyk** [comment] 2022-02-11 12:08
But it also might be a better long term fix to simply apply a change in the platform's UI logic. (e.g. Don't ever show mapping for any trigger even if `metadata.in` is defined.)

**Comment by khanzadyan** [comment] 2022-02-11 12:31
@jhorbulyk why we have this `"in": {},` anyway? Can't find this in any other component's trigger function.

**Comment by jhorbulyk** [comment] 2022-02-11 12:34
Closing in favor of https://github.com/elasticio/elasticio/issues/6009

**Closed by jhorbulyk** 2022-02-11 12:34 UTC
Labels: bug, enhancement
